package com.example.Course.Hub.REPOSITORY;

import com.example.Course.Hub.ENTITY.Lesson;
import org.springframework.data.jpa.repository.JpaRepository;


import java.util.List;
import java.util.Optional;


/**
 * LessonRepository — JPA repository for Lesson entity.
 *
 * ════════════════════════════════════════════════════════════
 * KEY FIX: findByCourse_CourseIdAndLessonId(courseId, lessonId)
 *
 * WHY IT'S NEEDED:
 *   lessonId is a trainer-defined integer that RESTARTS at 1 for
 *   every course (Lesson 1 of SpringBoot, Lesson 1 of Python, etc.)
 *   So fetching by lessonId alone is AMBIGUOUS — it can return the
 *   wrong lesson from a different course.
 *
 *   This method uses BOTH the parent courseId AND the lessonId,
 *   which together uniquely identify a lesson.
 *
 * SQL generated by JPA:
 *   SELECT * FROM lesson l
 *   JOIN course c ON l.course_id = c.id
 *   WHERE c.course_id = ? AND l.lesson_id = ?
 *   LIMIT 1
 *
 * findByCourse_CourseId(courseId)
 *   SQL: SELECT * FROM lesson WHERE course_id = (SELECT id FROM course WHERE course_id = ?)
 *   Used for fetching all lessons of a course efficiently (avoids loading Course object first).
 * ════════════════════════════════════════════════════════════
 */

public interface LessonRepository extends JpaRepository<Lesson , Integer> {





    /**
     * Find a specific lesson by its parent courseId AND its lessonId.
     *
     * "course_courseId" → Spring Data reads this as:
     *   lesson.course (the @ManyToOne field) → .courseId (field in Course)
     *
     * Usage in StudentController:
     *   Lesson lesson = lessonRepo
     *       .findByCourse_CourseIdAndLessonId(courseId, lessonId)
     *       .orElseThrow(...);
     *
     * @param courseId  The business courseId string (e.g. "JAVA101")
     * @param lessonId  The trainer-defined lesson number (e.g. 1, 2, 3)
     * @return Optional<Lesson> — present if found, empty if not
     */
    Optional<Lesson> findByCourse_CourseIdAndLessonId(String courseId, int lessonId);

    /**
     * Find all lessons for a specific course.
     * More efficient than loading the Course entity and calling getLessons()
     * because this avoids the Course fetch entirely.
     *
     * @param courseId  The business courseId string (e.g. "JAVA101")
     * @return List<Lesson> sorted by DB insertion order (add ORDER BY if needed)
     */
    List<Lesson> findByCourse_CourseId(String courseId);





}
